version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_giikucamp
    environment:
      POSTGRES_USER: giikucamp20
      POSTGRES_PASSWORD: camp
      POSTGRES_DB: giikucamp20
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
